name: Run newday data

on:
  schedule:
    # UTC+0 기준 15시가 한국(UTC+9)의 자정!
    - cron: '0 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update daily data to DB
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Generate env variables for DB update
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: echo "DBURI=$MONGODB_URI" >> .env

      - name: Install npm dependencies
        run: npm ci

      - name: Update daily data
        run: npm run newday
